spring.application.name=question-service
server.port=${PORT}

spring.config.import=configserver:${CONFIG_SERVER_URL}
spring.cloud.config.fail-fast=true
spring.cloud.config.request-connect-timeout=2000
spring.cloud.config.request-read-timeout=5000
spring.cloud.config.retry.max-attempts=6
spring.cloud.config.retry.initial-interval=1000
spring.cloud.config.retry.max-interval=2000
spring.cloud.config.retry.multiplier=1.5

server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=20s
