spring.application.name=gateway

spring.config.import=${CONFIG_SERVER_IMPORT:optional:configserver:http://localhost:8888}
spring.cloud.config.fail-fast=${CONFIG_SERVER_FAIL_FAST:false}
spring.cloud.config.request-connect-timeout=${CONFIG_SERVER_CONNECT_TIMEOUT:2000}
spring.cloud.config.request-read-timeout=${CONFIG_SERVER_READ_TIMEOUT:5000}
spring.cloud.config.retry.max-attempts=${CONFIG_SERVER_MAX_ATTEMPTS:6}
spring.cloud.config.retry.initial-interval=${CONFIG_SERVER_INITIAL_INTERVAL:1000}
spring.cloud.config.retry.max-interval=${CONFIG_SERVER_MAX_INTERVAL:2000}
spring.cloud.config.retry.multiplier=${CONFIG_SERVER_MULTIPLIER:1.5}
