document.title=Regulamento dos Cursos de Graduacao da UFRN
document.resolution=Resolucao no 016/2023-CONSEPE
document.version=2023-016
document.official-url=https://sig.ufrn.br/download/sigaa/public/regulamento_dos_cursos_de_graduacao.pdf
document.sha256=794d80665c84f18b117a71a2befc3d642fbc836aeff532057fa516dc8fdeab3b
