eureka.instance.hostname=${EUREKA_INSTANCE_HOSTNAME}
eureka.instance.instance-id=${spring.application.name}:${eureka.instance.hostname}:${server.port}
eureka.instance.metadata-map.gateway-exposed=true
eureka.client.service-url.defaultZone=${EUREKA_URL}
eureka.client.registry-fetch-interval-seconds=5

downstream.normalizer-url=http://question-normalizer/normalizeQuestion
downstream.rag-graphql-url=http://rag-service/graphql
downstream.normalizer-timeout=1s
downstream.rag-timeout=3s

management.endpoint.health.show-details=always
management.tracing.sampling.probability=${TRACING_SAMPLING_PROBABILITY}
management.zipkin.tracing.endpoint=${ZIPKIN_ENDPOINT}
management.endpoints.web.exposure.include=health,info,metrics,prometheus,refresh

logging.pattern.correlation=[${spring.application.name:question-service},%X{traceId:-},%X{spanId:-}]
